---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Install Protoc
        uses: arduino/setup-protoc@master
      - name: Compile protobuf
        run: |
          protoc --python_out=. badconga/app/schema.proto
      - name: Lint code
        run: |
          pylint --ignore=schema_pb2.py badconga
